// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply plugin: 'com.huawei.ohos.app'

//For instructions on signature configuration, see https://developer.harmonyos.com/cn/docs/documentation/doc-guides-V3/ide_debug_device-0000001053822404-V3#section1112183053510
ohos {
    signingConfigs {
        debug {
            storeFile file('C:\\Users\\tarca\\Desktop\\silme.amk.windowsu\\astroclock.p12')
            storePassword '0000001C8127E68D1958627B60623A17E9015D112226A915EC30B6078FAAA74DD1D510E9C1BBFB8368E793F6'
            keyAlias = 'ananinamcigihuawei'
            keyPassword '0000001C91843E10C538E58602CCD19CA7F8C195A8B9AE19488DDCA4C3238C30C9FC777FBC73C739D0BAB19A'
            signAlg = 'SHA256withECDSA'
            profile file('C:\\Users\\tarca\\Desktop\\silme.amk.windowsu\\com.example.astroclockDebug.p7b')
            certpath file('C:\\Users\\tarca\\Desktop\\silme.amk.windowsu\\astroclock.cer')
        }
    }
    compileSdkVersion 5
}

buildscript {
    repositories {
        maven {
            url 'https://repo.huaweicloud.com/repository/maven/'
        }
        maven {
            url 'https://developer.huawei.com/repo/'
        }
    }
    dependencies {
        classpath 'com.huawei.ohos:hap:3.1.5.0'
        classpath 'com.huawei.ohos:decctest:1.2.7.20'
    }
}

allprojects {
    repositories {
        maven {
            url 'https://repo.huaweicloud.com/repository/maven/'
        }
        maven {
            url 'https://developer.huawei.com/repo/'
        }
    }
}
